#include "LionspeciesApp.h"
#include "Moose.h"
#include "AppFactory.h"
#include "MooseSyntax.h"

template<>
InputParameters validParams<LionspeciesApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  params.set<bool>("use_legacy_output_syntax") = false;

  return params;
}

LionspeciesApp::LionspeciesApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);
  LionspeciesApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  LionspeciesApp::associateSyntax(_syntax, _action_factory);
}

LionspeciesApp::~LionspeciesApp()
{
}

// External entry point for dynamic application loading
extern "C" void LionspeciesApp__registerApps() { LionspeciesApp::registerApps(); }
void
LionspeciesApp::registerApps()
{
  registerApp(LionspeciesApp);
}

// External entry point for dynamic object registration
extern "C" void LionspeciesApp__registerObjects(Factory & factory) { LionspeciesApp::registerObjects(factory); }
void
LionspeciesApp::registerObjects(Factory & factory)
{
}

// External entry point for dynamic syntax association
extern "C" void LionspeciesApp__associateSyntax(Syntax & syntax, ActionFactory & action_factory) { LionspeciesApp::associateSyntax(syntax, action_factory); }
void
LionspeciesApp::associateSyntax(Syntax & /*syntax*/, ActionFactory & /*action_factory*/)
{
}
